#!/usr/bin/perl -w

# suterm - A stupid simple way to get a root shell in GNOME. It requires you to
# have /etc/sudoers set up for your username with the NOPASSWD option.
#
# Create a launcher that runs this script and check "Open in Terminal". Then
# the launcher will open a root gnome-terminal, provided `sudo -i` normally
# doesn't require you to enter a password.
#
# --Kirsle
# http://sh.kirsle.net/

use strict;
use warnings;

system ("sudo -i");
exit(0);
